config/routes.rb
Rails.application.routes.draw do
  root to: 'albums#index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "users" do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end
  resources :albums

  # login/out actions
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  # follow/unfollow actions
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  put '/albums/:id/earn_coin_for_view', to: "albums#earn_coin_for_view", as: "earn_coin_for_view"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :user
    has_many_attached :images
    validates :name, presence: true, uniqueness: { scope: :user_id }
    validates :images, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..10.megabytes }

    def resize_image input
        return self.images[input].variant(resize: '500x500!').processed
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :albums
  has_one_attached :image

  # users can have followers
  # Join table ref
  has_many :following_users, foreign_key: :followee_id, class_name: 'Relationship'  
  # User table ref
  has_many :followers, through: :following_users

  # users can follow who they want
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Relationship'
  has_many :followees, through: :followed_users
  
  validates :email, presence: true, uniqueness: true

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login
  before_action :set_album, only: [:show, :edit, :update, :destroy, :earn_coin_for_view]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit 
    # @user = User.find(params[:id])
    if current_user.id != @album.user_id 
      redirect_to albums_url
    else
      render :edit
    end
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # Testing other methods
  def earn_coin_for_view()
    @index = params[:index].to_i
    if current_user.id != @album.user.id
      @album.user.increment! :coins
    end
    redirect_to @album.images[@index]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:user_id, :name, :description, :privacy, images: [])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
    before_action :redirect_signed_in_users, only: [:create, :new]
    before_action :find_user, only: [:show, :edit, :update, :destroy]
    before_action :require_login, only: [:show, :edit]

    # GET /users/1
    # GET /users/1.json
    def show
      @albums = @user.albums
      @followers = @user.followers
      @followees = @user.followees
    end

    # GET /users/new
    def new
        @user = user_from_params
        render template: "users/new"
    end
  
    # GET /users/1/edit
    def edit 
      if current_user.id != @user.id 
        redirect_to current_user
      else
        render :edit
      end
    end

    # POST /users
    # POST /users.json
    def create
        @user = user_from_params
            if @user.save
                sign_in @user
                redirect_back_or url_after_create
            else
                render template: "users/new"
            end
    end
  
    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'user was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
        @user.destroy
        respond_to do |format|
        format.html { redirect_to users_url, notice: 'user was successfully destroyed.' }
        format.json { head :no_content }
        end
    end

    # POST /users/1/follow
    def follow
      @user = User.find(params[:id])
      current_user.followees << @user
      redirect_to user_path(@user)
    end  
    
    # POST /users/1/unfollow 
    def unfollow
      @user = User.find(params[:id])
      current_user.followed_users.find_by(followee_id: @user.id).destroy
      redirect_to user_path(@user)
    end
    
    private
    def redirect_signed_in_users
        if signed_in?
            redirect_to Clearance.configuration.redirect_url
        end
    end

    def url_after_create
        Clearance.configuration.redirect_url
    end

    def user_params
        params.require(:user).permit(:email, :password, :image, :location, :name)
    end

    def find_user
        @user = User.find(params[:id])
    end 

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<div class="login_container">
    <div class="login_path">
    <h1>Edit Album: <%=@album.name %></h1>
    <%= render 'form', album: @album %>

    <%= link_to 'Show', @album %> 
    <%= link_to 'Back', albums_path %>
    </div>
</div>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<div class="floating_action_btn">
  <%= link_to '+', new_album_path %>
</div>

<br>

<div class="album_con">
  <% @albums.each do |album| %>
      <div class="album">
        <p><%= link_to image_tag(album.resize_image(0), :class => "image_index"), album %></p>
        <div class="album_details">
          <p><%= album.name %></p>
          <p>Description: <%= album.description %></p>
          <% if current_user.id == album.user_id %>
            <div class="index_actions">
              <p><%= link_to 'Edit', edit_album_path(album) %></p>
              <p><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
</div>

app/views/albums/new.html.erb
<div class="login_container">
    <div class="login_path">
    <h1>New Album</h1>
    <%= render 'form', album: @album %>

    <%= link_to 'Back', albums_path %>
    </div>
</div>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @album.description %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @album.user.email, @album.user %>
</p>

<% if @album.images.attached? %>
    <% @album.images.each_with_index do |image, index| %>
        <%= link_to image_tag(@album.resize_image(index), class: "album_show_image"), earn_coin_for_view_path(index: index), method: :put %>
    <% end %>
<% end %>

<% if current_user.id == @album.user_id %>
    <%= link_to 'Edit', edit_album_path(@album) %> |
    <%= link_to 'Destroy', @album, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CameraRoll</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> -->
    <%= stylesheet_link_tag 'style.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <header>
    <div class="row head_con">
      <%= link_to albums_path do %>
        <div class="logo_con">
          <h1>CameraRoll 📸</h1>
        </div>
      <% end %>
      <% if signed_in? %>
        <div class="signed_in">
          Signed in as: <%= link_to current_user.email, current_user%>
          <%= button_to 'Sign out', sign_out_path, method: :delete %>
        </div>
    </div>
      <% else %>
    </header>

  <div class="container">
    <div class="login_container">
      <section class="login_path">
        <div id="flash">
          <% flash.each do |key, value| %>
            <div class="flash <%= key %>"><%= value %></div>
          <% end %>
        </div>
        <% end %>
        <%= yield %>
      </section>
    </div>
  </div>

    <footer>
      <section>
        <h5> Richard Wahba © </h5>
      </section>
    </footer>
  </body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="text-field">
  <%= form.label :name %>
  <%= form.text_field :name, type: 'name' %>
</div>

<div class="text-field">
  <%= form.label :location %>
  <%= form.text_field :location, type: 'location' %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>
     <div class="submit-field">
      <%= form.submit %>
    </div>
  <% end %>

<%= link_to 'Back', @user %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="login_container">
  <div class="login_path">
  <div>
    <p>
      <strong>Name:</strong>
      <%= @user.email %>
    </p>
    <p>
      <strong>Followers:</strong>
      <%= @user.followers.length %>
       <strong>Following:</strong>
      <%= @user.followees.length %>
      <% if current_user != @user %>
        <% if current_user.followees.include?(@user) %>   
          <h5><%= button_to "Unfollow #{@user.name}", unfollow_user_path, method: "POST" %></h5>
        <% else %>   
          <h5><%= button_to "Follow #{@user.name}", follow_user_path, method: "POST"  %></h5>
        <% end %>
      <% end %>
    </p>
  </div>

  <p>
    <strong>Location:</strong>
    <%= @user.location %>
  </p>

  <% if current_user.id == @user.id %>
      <strong>Coins:<strong>
      <%= current_user.coins%>
      <br>
      <strong><%= link_to 'Edit', edit_user_path(@user) %><strong>
  <% end %>
  <%= link_to 'Back', albums_path %>
  </div>
</div>